### ISSUE TITLE
js-paloma-hook div being removed from the page causing Turbolinks 5 trouble

### ISSUE THREAD

**Issue by brendon** [gnclmorais/paloma#6]
See: https://github.com/kbparagua/paloma/issues/101

Another name for this could be 'make Paloma idempotent'. @gnclmorais, what are your thoughts on removing the code that removes the Paloma hook from the page on initialisation? :)

**Comment by gnclmorais** [comment]
Hey @brendon, sorry for the late reply! I’m catching up on my notifications here…
On the [discussion you linked to](https://github.com/kbparagua/paloma/issues/101#issuecomment-254339469), it seems you had a working prototype… Would you like to open a PR with the idea implemented so we can discuss it further?

**Comment by brendon** [comment]
Hi @gnclmorais, thanks for following this up. I've had a stab at it. :) Let me know what you think.
