### ISSUE TITLE
Add helper methods for testing?

### ISSUE THREAD

**Issue by Martin-Nyaga** [gnclmorais/paloma#9]
It would be very useful from a testing point of view to be able to make assertions about the parameters passed to Paloma as part of a Rails integration test, as they are sometimes the main output of the Rails controller. Unfortunately, Paloma does not have any utilities to allow for this. You can dig into `@controller` and get the paloma instance from the action controller:
```ruby
paloma_instance = @controller.send(:paloma)
```
but because Paloma calls `clear_request` after serving the view hook, you won't be able to get access to the parameters that were passed to the view:
```ruby
paloma_instance.params #=> returns {}
```

I've been able to work around this by monkey patching `Paloma::Controller` in the test environment to store a history of requests served by Paloma. I've also added a `Paloma::TestHelper` module which can be included into `ActiveSupport::TestCase` or `ActionDispatch::IntegrationTest` to allow easy access to the params:

```ruby
# test/support/paloma_extensions.rb
module Paloma
  class Controller
    if ::Rails.env.test?
      attr_reader :request_history
    end

    def clear_request
      if ::Rails.env.test?
        @request_history ||= []
        @request_history.push(self.request)
      end

      self.resource = nil
      self.action = nil
      self.params = {}
      true
    end
  end

  module TestHelper
    def paloma_params
      @paloma_params ||= @controller.send(:paloma).request_history.last[:params]
    end
  end
end
```

Then from any Integration test:

```ruby
include Paloma::TestHelper

paloma_params #=> Returns the last set of params passed to paloma
```

Perhaps this is something which could be built in to the gem? I'm happy to submit a PR with these changes.

**Comment by gnclmorais** [comment]
Hey @Martin-Nyaga! Sorry about the _laaate_ reply to this, somehow I found it deep in my mails. 😞 

You’re proposing an interesting idea, would you give me more details about the use case you have, please? Maybe an example of a test you have so I better understand it? Thanks!

**Comment by Martin-Nyaga** [comment]
Hey @gnclmorais, no worries. Better late than never. 😄 

The use case is fairly simple. Here's an example (summarised) from our codebase where we've been using the above extension to test this for nearly a year. We are using minitest.

Controller:
```ruby
class TagNodesController
  def show
    # ... some processing here ...
    js tags: @node.tags.map(&:into_variable).map(&:attributes)

    render layout: "simple"
  end
end                                                                              
```

Test:
```ruby
require "support/paloma_extensions"

class TagNodesControllerTest < ActionDispatch::IntegrationTest
  include Paloma::TestHelper

  test "should get show page for a specific node" do
    #... some set up here ...
    get tag_node_url(workspace, origin, "TEST")
    assert_response :success
    assert_equal variables.map(&:attributes).sort, paloma_params[:tags].sort
  end
end
```

The point of this code is that we are passing some data (tags) to JS to initialise some client-side components in the paloma controller which require the tags as input. When testing the rails controller, we want to test not only that the request was successful, but that the right params were passed to the paloma controller. That's where the `paloma_params` helper method is useful.

**Comment by gnclmorais** [comment]
Hey @Martin-Nyaga! Again, sorry for the long reply… I see your use case now, it feels like something the gem could use. I was thinking of providing it as a helper people could include from their tests, just as you have it. This would keep the gem working as is and, if people need it, could bring the helper into their own tests. What do you think? I would be happy to review a PR with that, if you want to add your code to the gem. 😃 Let me know what you think!

**Comment by Martin-Nyaga** [comment]
Hey @gnclmorais, no problem! Yeah I'd be happy to submit a PR, with essentially the same approach as the monkey-patch above. I can do so (hopefully) over the next few days. Do you have any thoughts on the name `paloma_params` for the helper method? Perhaps something like `js_params` could be more consistent with the `js` method in the controller?

**Comment by gnclmorais** [comment]
I like that suggestion! Love the `js` ⇆ `js_params` connection 👌
